### PR TITLE
change way to get client config

### PR DESCRIPTION
**Pull request by jiuker**
easy way to get client config

This closes #

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed

## Local Testing

Please ensure you run the unit, integration and system tests before approving the PR.

To run the unit and integration tests:

```
$ make unit-tests integration-tests
```

You will need to target a k8s cluster and have the operator deployed for running the system tests.

For example, for a Kubernetes context named `dev-bunny`:
```
$ kubectx dev-bunny
$ make destroy deploy-dev
# wait for operator to be deployed
$ make system-tests
```

### CODE REVIEW

**Review by jiuker — COMMENTED** [review]
Creating a new project based on the operator-sdk can be found to be common in this usage

**Review by jiuker — COMMENTED** [review]
// GetConfig creates a *rest.Config for talking to a Kubernetes API server.
// If --kubeconfig is set, will use the kubeconfig file at that location.  Otherwise will assume running
// in cluster and use the cluster provided kubeconfig.
//
// It also applies saner defaults for QPS and burst based on the Kubernetes
// controller manager defaults (20 QPS, 30 burst)
//
// Config precedence
//
// * --kubeconfig flag pointing at a file
//
// * KUBECONFIG environment variable pointing at a file
//
// * In-cluster config if running in cluster
//
// * $HOME/.kube/config if exists.
it's tell us how to use config.GetConfigOrDie().

**Review by Zerpet — APPROVED** [review]
Tried this locally and it worked well for me.

**Comment by Zerpet** [comment]
Thank you!

**Pull request merged**
