### PR TITLE
Missing dash on kubectl-rabbitmq command line tool

### PR DESCRIPTION
**Pull request by Gsantomaggio**
## Summary Of Changes
Add missing dash on the help section

### CODE REVIEW

**Comment by mkuratczyk** [comment]
This dash is not missing. This is a `kubectl` plugin - when you put it on you PATH, `kubectl rabbitmq` (without a dash) will work. More info here: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by Gsantomaggio** [comment]
Thank you @mkuratczyk I didn't think about the plugin.

Maybe a few documentation is needed about that !

**Comment by mkuratczyk** [comment]
Coming soon to a rabbitmq.com near you ;)
https://github.com/rabbitmq/rabbitmq-website/pull/1060

**Comment by Gsantomaggio** [comment]
Amazing! Thanks a lot

**Pull request closed without merging**
