### PR TITLE
Proposal to reduce size of CRD

### PR DESCRIPTION
**Pull request by coro**

### CODE REVIEW

**Comment by mkuratczyk** [comment]
Is it possible to strip the descriptions of the embedded fields only (basically anything under `spec.override`)?

**Comment by coro** [comment]
> Is it possible to strip the descriptions of the embedded fields only (basically anything under `spec.override`)?

Unfortunately not. I saw a suggestion in the [k/k issue](https://github.com/kubernetes/kubernetes/issues/82292#issuecomment-601851309) that allowed kubebuilder to recursively skip description generation for fields with a `// +kubebuilder:` tag, but nothing like it is implemented yet.

**Review by ChunyiLyu — APPROVED** [review]
Looks great! 😸

**Comment by mkuratczyk** [comment]
It's actually 0, not -1, that make `controller-gen` drop CRD descriptions.

**Comment by coro** [comment]
> It's actually 0, not -1, that make `controller-gen` drop CRD descriptions.

Ah, they changed it due to review feedback, fair enough. - https://github.com/kubernetes-sigs/controller-tools/pull/299#discussion_r312586273

**Review by mkuratczyk — APPROVED** [review]

**Pull request merged**
