### PR TITLE
Implement service binding Provisioned Service duck type

### PR DESCRIPTION
**Pull request by scothis**
The Service Binding Specification for Kubernetes defines a mechanism for
application to consume services in a consistent way. In order to reduce
frication for users consuming a service, the service can advertise the
credentials for its service by implementing a Provisioned Service duck
type.

See https://github.com/k8s-service-bindings/spec#provisioned-service

- adds `.status.binding.name` as a reference to the admin secret
- the admin secret contains the required `type` key with the value
  "rabbitmq" and additional connection fields like: scheme, host, port
  and uri
- adds a new ClusterRole granting the Service Binding controller access
  to read RabbitmqCluster resources

### CODE REVIEW

**Comment by ChunyiLyu** [comment]
@scothis Hey Scott, I remember from our meeting that you said that the PR needs some manual testing, and I'm wondering what the status of this work now?

**Comment by scothis** [comment]
@ChunyiLyu thanks for the nudge. I still intend to do that, but got sidetracked...

**Comment by MirahImage** [comment]
@scothis we've noticed that this PR has gone rather stale and needs some work to rebase it onto the current state of main. We also got a quesiton from @Samze about the status of RabbitMQ support for bindings ducktypes. Any updates?

**Comment by scothis** [comment]
@MirahImage let's close this PR and circle back on how to best expose a provisioned service next week.

**Pull request closed without merging**
