### PR TITLE
Removing Helm chart to deploy RabbitmqCluster object

### PR DESCRIPTION
**Pull request by Zerpet**
**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed

## Summary Of Changes
We are not expecting this chart to be in use, and we no longer use it internally.

## Additional Context
N/A

## Local Testing
Tests and packaging tasks have been removed from CI.

### CODE REVIEW

**Review by MirahImage — APPROVED** [review]

**Comment by kvendingoldo** [comment]
@Zerpet can you tell why Helm was deleted? Should I use kubectl plugin instead?

**Comment by Zerpet** [comment]
@kvendingoldo the main reason was adoption. Since we didn't publish this chart to Helm Hub, and it was used mostly within our team, we believe this chart was not used at all. I use the kubectl plugin nowadays to deploy RabbitmqCluster objects.

**Comment by MarcialRosales** [comment]
@politician [bitnami cluster-operator helm chart](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq-cluster-operator/) is an officially maintained chart. It is been actively maintained and tested against latest [RabbitMQ kubernetes cluster-operator](https://github.com/rabbitmq/cluster-operator) by bitnami team.

**Comment by politician** [comment]
@MarcialRosales Ok I didn't know it was considered as the official chart. Maybe the [official documentation](https://www.rabbitmq.com/kubernetes/operator/install-operator.html) should reflect that? I must say, I am always looking for the Helm install instructions because I know my life will be easier for my workflow (GitOps) and am sure many others are in the same boat.

**Pull request merged**
